// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xtv2uahK1TpvlZPyoTe82Ro7U7ASD3s',
    appId: '1:158817110830:web:43d2ed3db5eadd441fc8bf',
    messagingSenderId: '158817110830',
    projectId: 'proyecto-multiplataforma-dam2',
    authDomain: 'proyecto-multiplataforma-dam2.firebaseapp.com',
    storageBucket: 'proyecto-multiplataforma-dam2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWv8FgnTRU9X-XpkWp1IOIhxspHHVC2w',
    appId: '1:158817110830:android:7c82dd714cd41e721fc8bf',
    messagingSenderId: '158817110830',
    projectId: 'proyecto-multiplataforma-dam2',
    storageBucket: 'proyecto-multiplataforma-dam2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABN04p3ARHd65fcOPJ0rbJfwwo4dQuo3o',
    appId: '1:158817110830:ios:2fc9faa0d4b973ef1fc8bf',
    messagingSenderId: '158817110830',
    projectId: 'proyecto-multiplataforma-dam2',
    storageBucket: 'proyecto-multiplataforma-dam2.firebasestorage.app',
    iosClientId: '158817110830-vq4fthsv7hic8fv383j807296c9adpiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuaderno1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABN04p3ARHd65fcOPJ0rbJfwwo4dQuo3o',
    appId: '1:158817110830:ios:2fc9faa0d4b973ef1fc8bf',
    messagingSenderId: '158817110830',
    projectId: 'proyecto-multiplataforma-dam2',
    storageBucket: 'proyecto-multiplataforma-dam2.firebasestorage.app',
    iosClientId: '158817110830-vq4fthsv7hic8fv383j807296c9adpiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuaderno1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1xtv2uahK1TpvlZPyoTe82Ro7U7ASD3s',
    appId: '1:158817110830:web:5e8b45b68355ca0e1fc8bf',
    messagingSenderId: '158817110830',
    projectId: 'proyecto-multiplataforma-dam2',
    authDomain: 'proyecto-multiplataforma-dam2.firebaseapp.com',
    storageBucket: 'proyecto-multiplataforma-dam2.firebasestorage.app',
  );
}
